# Netlify build settings
[build]
  publish = "."
  command = "echo 'No build needed - static files'"

# Headers for PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Manifest headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Redirects for SPA (if needed in future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
